# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      # - id: check-added-large-files

  - repo: local
    hooks:
      - id: textlint
        name: textlint
        language: node
        entry: npm run textlint
        files: '^.*\.(sty|tex|md)?$'

  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.23.9
    hooks:
      - id: latexindent
        name: latexindent
        files: '^src/.*\.tex$'

  # - repo: local
  #   hooks:
  #     - id: latexmk
  #       name: latexmk
  #       entry: make prod
  #       language: system
  #       files: '^src/.*\.tex$'
